version: "2"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: true
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  identical-code:
    enabled: true

plugins:
  phpmd:
    enabled: true
  sonar-php:
    enabled: true

exclude_patterns:
  - "spec/"
  - "!spec/support/helpers"
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
  - ".phpstorm.meta.php"
  - "_ide_*"
  - "public/"
  - "resources/lang/"
  - "database/migrations/"
  - "storage/"
  - "bootstrap/"
