
language: php

php:
  - "7.1"

before_script:
  - cp .env.testing .env
  - mysql -e 'create database translations;'
  - composer self-update
  - composer global require hirak/prestissimo
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed

services:
  - mysql

script:
  - vendor/bin/phpunit

after_script:
  - ./codeclimate.sh